const key='racktrack-web-v1';
const stored=JSON.parse(localStorage.getItem(key)||'null');
const legacyPhotos=Array.isArray(stored?.photos)?stored.photos.filter(x=>typeof x==='string'&&x.startsWith('data:image/')):[];
const state=stored||{name:'Rack 01',location:'',rackId:'',units:42,devices:[{name:'Patchpanel 48 Port',u:41,h:1,vendor:'',model:''},{name:'Cisco C9300',u:39,h:1,vendor:'Cisco',model:'C9300-48P'},{name:'Q-SYS Core Nano',u:36,h:1,vendor:'Q-SYS',model:'Core Nano'},{name:'APC UPS',u:2,h:3,vendor:'APC',model:''}]};
delete state.photos;
const $=q=>document.querySelector(q);
function save(){localStorage.setItem(key,JSON.stringify(state))}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('racktrack-media',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('photos'))r.result.createObjectStore('photos',{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbAdd(blob,name='Rack-Foto'){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite');const req=tx.objectStore('photos').add({blob,name,createdAt:Date.now()});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbAll(){const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction('photos','readonly').objectStore('photos').getAll();req.onsuccess=()=>resolve(req.result.sort((a,b)=>b.createdAt-a.createdAt));req.onerror=()=>reject(req.error)})}
async function dbDelete(id){const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction('photos','readwrite').objectStore('photos').delete(id);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)})}
function dataURLtoBlob(url){const [head,data]=url.split(',');const mime=(head.match(/data:(.*?);/)||[])[1]||'image/jpeg';const bytes=atob(data);const arr=new Uint8Array(bytes.length);for(let i=0;i<bytes.length;i++)arr[i]=bytes.charCodeAt(i);return new Blob([arr],{type:mime})}
async function compressImage(file){const img=await createImageBitmap(file);const max=2048;const scale=Math.min(1,max/Math.max(img.width,img.height));const w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);return await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',0.82))}
async function migrateLegacyPhotos(){if(!legacyPhotos.length)return;try{save()}catch(e){localStorage.removeItem(key);save()}for(const src of legacyPhotos){try{await dbAdd(dataURLtoBlob(src),'Migriertes Foto')}catch(e){console.warn('Foto-Migration fehlgeschlagen',e)}}}
function renderRack(){const el=$('#rackView');el.innerHTML='';for(let u=state.units;u>=1;u--){const row=document.createElement('div');row.className='urow';row.innerHTML=`<div class="u">${u}U</div><div class="slot"></div>`;const d=state.devices.find(x=>x.u===u);if(d){const dev=document.createElement('div');dev.className='device';dev.style.height=`calc(${d.h*38}px - 6px)`;dev.innerHTML=`<strong>${d.name}</strong><small>${d.vendor||''} ${d.model||''} · ${d.h}U</small>`;row.querySelector('.slot').appendChild(dev)}el.appendChild(row)}$('#title').textContent=state.name;$('#meta').textContent=`${state.units}U · 19\" · Front`}
function renderDevices(){const el=$('#deviceList');el.innerHTML='';[...state.devices].sort((a,b)=>b.u-a.u).forEach(d=>{const item=document.createElement('div');item.className='item';item.innerHTML=`<div><strong>${d.name}</strong><div class="muted">U${d.u}${d.h>1?'–U'+(d.u+d.h-1):''} · ${d.h}U · ${d.vendor||''} ${d.model||''}</div></div><button>×</button>`;item.querySelector('button').onclick=()=>{state.devices.splice(state.devices.indexOf(d),1);save();renderAll()};el.appendChild(item)})}
async function renderPhotos(){const el=$('#photoGrid');el.innerHTML='<p class="muted">Fotos werden geladen…</p>';let photos=[];try{photos=await dbAll()}catch(e){el.innerHTML='<p class="muted">Fotospeicher konnte nicht geöffnet werden.</p>';return}el.innerHTML='';if(!photos.length){el.innerHTML='<p class="muted">Noch keine Fotos.</p>';return}photos.forEach((p,i)=>{const wrap=document.createElement('div');wrap.style.position='relative';const img=new Image();const url=URL.createObjectURL(p.blob);img.src=url;img.alt=p.name||`Rack-Foto ${i+1}`;img.onload=()=>URL.revokeObjectURL(url);const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label','Foto löschen');del.style.position='absolute';del.style.top='8px';del.style.right='8px';del.style.padding='6px 9px';del.onclick=async()=>{await dbDelete(p.id);renderPhotos()};wrap.append(img,del);el.appendChild(wrap)})}
function renderAll(){$('#units').value=state.units;$('#projectName').value=state.name;$('#location').value=state.location;$('#rackId').value=state.rackId;renderRack();renderDevices();renderPhotos()}
async function addPhotoFiles(files){for(const f of [...files].filter(f=>f.type.startsWith('image/'))){try{const blob=await compressImage(f);if(!blob)throw new Error('Komprimierung fehlgeschlagen');await dbAdd(blob,f.name||'Rack-Foto')}catch(err){console.error(err);alert('Foto konnte nicht gespeichert werden. Bitte prüfe den verfügbaren Safari-Speicher.')}}renderPhotos()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.id).classList.add('active')});
$('#units').onchange=e=>{state.units=+e.target.value;save();renderRack()};
$('#addDevice').onclick=()=>$('#dialog').showModal();
$('#deviceForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const d={name:$('#dName').value.trim(),u:+$('#dU').value,h:+$('#dH').value,vendor:$('#dVendor').value.trim(),model:$('#dModel').value.trim()};if(d.u<1||d.u+d.h-1>state.units){e.preventDefault();alert('Gerät liegt außerhalb des Racks.');return}state.devices.push(d);save();setTimeout(renderAll,0)});
$('#photoCamera').onchange=e=>{if(e.target.files?.length)addPhotoFiles(e.target.files);e.target.value=''};
$('#photoUpload').onchange=e=>{if(e.target.files?.length)addPhotoFiles(e.target.files);e.target.value=''};
$('#analyze').onclick=async()=>{const photos=await dbAll();alert(photos.length?'Foto gespeichert. Automatische OCR/Frontplatten-Erkennung folgt als nächster Analysebaustein.':'Bitte zuerst ein Rack-Foto aufnehmen oder hochladen.')};
$('#saveProject').onclick=()=>{state.name=$('#projectName').value.trim()||'Rack';state.location=$('#location').value.trim();state.rackId=$('#rackId').value.trim();save();renderAll();alert('Projekt lokal gespeichert.')};
$('#exportProject').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.name.replace(/[^a-z0-9]/gi,'_')||'RackTrack')+'.json';a.click()};
$('#newRack').onclick=()=>{if(confirm('Neues Rack anlegen?')){Object.assign(state,{name:'Neues Rack',location:'',rackId:'',units:42,devices:[]});save();renderAll()}};
if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
(async()=>{await migrateLegacyPhotos();renderAll()})();